import { sql } from "@databases/mysql";
export default sql`CREATE DATABASE IF NOT EXISTS WALLET_DB;
USE WALLET_DB;
CREATE TABLE IF NOT EXISTS WALLET (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    WALLET_NAME TEXT,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS TRANSACT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    WALLET_ID INT,
    BALANCE DOUBLE NOT NULL,
    DESCRIPTION VARCHAR(500),
    FOREIGN KEY (WALLET_ID)
        REFERENCES WALLET(ID),
    TRANSACT_TYPE ENUM("DEBIT", "CREDIT", "FAILED_DEBIT", "FAILED_CREDIT"),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE PROCEDURE CURR_BALANCE(IN WALLET_ID INT, OUT TOTAL_BALANCE DOUBLE)
    BEGIN
        SELECT BALANCE INTO TOTAL_BALANCE FROM TRANSACT WHERE ID=WALLET_ID AND TRANSACT_TYPE IN ("DEBIT", "CREDIT") SORT BY CREATED_DATE limit 1;
    END;
CREATE TRIGGER BU_INSERT_TRANSACT
    BEFORE INSERT
    ON TRANSACT FOR EACH ROW
    BEGIN
        DECLARE CURRENT_BALANCE DOUBLE DEFAULT 0;
        call CURR_BALANCE(NEW.WALLET_ID, @CURRENT_BALANCE);
        IF CURRENT_BALANCE + NEW.AMOUNT < 0 THEN
            SET NEW.TRANSACT_TYPE = "FAILED_DEBIT";
            SET NEW.BALANCE = CURRENT_BALANCE;
        ELSEIF NEW.AMOUNT >= 0 THEN
            SET NEW.TRANSACT_TYPE = "CREDIT";
            SET NEW.BALANCE = CURRENT_BALANCE + NEW.AMOUNT;
        ELSE
            SET NEW.TRANSACT_TYPE = "DEBIT";
            SET NEW.BALANCE = CURRENT_BALANCE + NEW.AMOUNT;
        END IF;
    END;
`